/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDevicesStateRouteImport } from './routes/api.public.devices.state'
import { Route as ApiPublicAutomationsTickRouteImport } from './routes/api.public.automations.tick'

const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDevicesStateRoute = ApiPublicDevicesStateRouteImport.update({
  id: '/api/public/devices/state',
  path: '/api/public/devices/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAutomationsTickRoute =
  ApiPublicAutomationsTickRouteImport.update({
    id: '/api/public/automations/tick',
    path: '/api/public/automations/tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/api/public/automations/tick': typeof ApiPublicAutomationsTickRoute
  '/api/public/devices/state': typeof ApiPublicDevicesStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/api/public/automations/tick': typeof ApiPublicAutomationsTickRoute
  '/api/public/devices/state': typeof ApiPublicDevicesStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/api/public/automations/tick': typeof ApiPublicAutomationsTickRoute
  '/api/public/devices/state': typeof ApiPublicDevicesStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automations'
    | '/api/public/automations/tick'
    | '/api/public/devices/state'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automations'
    | '/api/public/automations/tick'
    | '/api/public/devices/state'
  id:
    | '__root__'
    | '/'
    | '/automations'
    | '/api/public/automations/tick'
    | '/api/public/devices/state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationsRoute: typeof AutomationsRoute
  ApiPublicAutomationsTickRoute: typeof ApiPublicAutomationsTickRoute
  ApiPublicDevicesStateRoute: typeof ApiPublicDevicesStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/devices/state': {
      id: '/api/public/devices/state'
      path: '/api/public/devices/state'
      fullPath: '/api/public/devices/state'
      preLoaderRoute: typeof ApiPublicDevicesStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automations/tick': {
      id: '/api/public/automations/tick'
      path: '/api/public/automations/tick'
      fullPath: '/api/public/automations/tick'
      preLoaderRoute: typeof ApiPublicAutomationsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationsRoute: AutomationsRoute,
  ApiPublicAutomationsTickRoute: ApiPublicAutomationsTickRoute,
  ApiPublicDevicesStateRoute: ApiPublicDevicesStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
